[project]
name = "wpp-whatsapp"
version = "0.5.3"
description = "WPP_Whatsapp aim of exporting functions from WhatsApp Web to the python, which can be used to support the creation of any interaction, such as customer service, media sending, intelligence recognition based on phrases artificial and many other things, use your imagination"

readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.2",
    "event-emitter-js>=0.1.2",
    "node-semver>=0.9.0",
    "pillow>=12.0.0",
    "playwright>=1.43.0",
    "playwright-stealth>=2.0.0",
    "playwrightsafethread>=0.5.5",
    "psutil>=7.1.2",
    "pyee>=13.0.0",
    "requests>=2.32.5",
    "segno>=1.6.6",
    "typing-extensions>=4.15.0",
]
